spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=auth
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

auth:
  jwt-secret: your-secret-key
  jwt-expiration-ms: 86400000
